// Copyright 2026 minutes contributors
// SPDX-License-Identifier: AGPL-3.0-only

import { existsSync } from 'node:fs';
import { join } from 'node:path';

import OS from '../ts/util/os/osMain.node.ts';

/**
 * Window / taskbar icon paths for minutes branding.
 * Generated by `pnpm run build:minutes-icons`.
 */
export function getMinutesWindowIconPath(rootDir: string): string {
  if (OS.isWindows()) {
    const icoPath = join(rootDir, 'build', 'icons', 'minutes', 'win', 'icon.ico');
    if (existsSync(icoPath)) {
      return icoPath;
    }
  }

  const pngPath = join(rootDir, 'build', 'icons', 'minutes', 'png', '512x512.png');
  if (existsSync(pngPath)) {
    return pngPath;
  }

  return join(rootDir, 'images', 'minutes', 'app-icon-source.png');
}

export function isMinutesBrandingEnabled(
  config: Readonly<{ has: (key: string) => boolean; get: (key: string) => unknown }>
): boolean {
  return config.has('storageProfile') && config.get('storageProfile') === 'minutes';
}
